import './resume.css';

export const metadata = {
  title: "Why, hello! I'm Daniel Lindsley.",
  // description: 'Generated by create next app',
};

export default function Layout(props) {
  return (
    <html>
      <body>
        {props.children}
      </body>
    </html>
  );
}
