import Image from 'next/image';

import '../globals.css';

import toastLogoMega from '../../../public/img/toast_logo_mega.png';

export const metadata = {
  title: 'Toast Driven',
  // description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body lang="en">
        <div className="mx-16 my-20 flex flex-row">
          <div className="mx-auto w-72 mt-4 grow-0 shrink-0">
            <Image
              src={toastLogoMega}
              alt="Toast Driven"
            />
          </div>

          <div className="ml-12 grow-0 shrink min-w-sm max-w-lg">
            <header>
              <h1 className="mb-6">
                <a href="/">Toast Driven</a>
              </h1>
            </header>

            <section id="content">
              {children}
            </section>

            <footer id="about">
              <p className="copyright">
                Established 2008 &mdash;
                Copyright {new Date().getFullYear()}
              </p>
            </footer>
          </div>

          <div className="grow shrink"></div>
        </div>
      </body>
    </html>
  );
}